### ISSUE TITLE
How to load evangelion-theme?

### ISSUE THREAD

**Issue by dbitouze** [crmsnbleyd/evangelion-theme#1]
Many thanks for your theme!

I installed its last version (`20240904.851`) but couldn't find out how to load it: `M-x load-theme` doesn't list it.

**Comment by crmsnbleyd** [comment]
The theme's name is simply `evangelion`, you could also make sure the package has been loaded

Thank you for trying out my theme!

**Comment by crmsnbleyd** [comment]
from my setup (using :straight t):
```elisp
(use-package evangelion-theme
    :config (load-theme 'evangelion t))
```

**Comment by dbitouze** [comment]
> from my setup (using :straight t):
> 
> ```emacs-lisp
> (use-package evangelion-theme
>     :config (load-theme 'evangelion t))
> ```

This is what I was missing, thanks. IMHO, it is worth to add this in the documentation (currently, the README).
